[Train] fix: _setup_train() world_size 기본값 추가
- world_size를 선택적 파라미터로 변경 (기본값=1)
- TypeError: missing 1 required positional argument 해결